[package]
name = "governance"                 
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
candid.workspace = true
serde.workspace = true
shared = { path = "../shared" }